mysite/urls.py
#!/usr/bin/python
#-*- coding: utf-8 -*-
"""mysite URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/4.0/topics/http/urls/
"""
from django.urls import re_path, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

import mysite.views as views


urlpatterns = [
    re_path(r'^$', views.index, name='index'),
    re_path(r'^admin/', admin.site.urls),

    re_path(r'^anunciante/sign_in/$', views.userSignIn, name='sign_in'),
    re_path(r'^anunciante/sign_out/$', views.userSignOut, name='sign_out'),

    re_path(r'^anunciante/$', views.anuncianteList, name='anuncianteList'),
    re_path(r'^anunciante/preNew/$', views.anunciantePreNew, name='anunciantePreNew'),
    re_path(r'^anunciante/preNew2/$', views.anunciantePreNew2, name='anunciantePreNew2'),
    re_path(r'^anunciante/new/$', views.anuncianteNew, name='anuncianteNew'),
    re_path(r'^anunciante/(?P<anuncianteId>[0-9]+)/$', views.anuncianteShow, name='anuncianteShow'),
    re_path(r'^anunciante/(?P<anuncianteId>[0-9]+)/password/$', views.userChangePassword, name='userChangePassword'),
    re_path(r'^anunciante/(?P<anuncianteId>[0-9]+)/delete/$', views.anuncianteDelete, name='anuncianteDelete'),
    re_path(r'^anunciante/(?P<anuncianteId>[0-9]+)/edit/$', views.anuncianteEdit, name='anuncianteEdit'),
    re_path(r'^anunciante/new/password/$', views.userPasswordNew, name='userPasswordNew'),
    re_path(r'^anunciante/new/password/(?P<token>\w+)/$', views.userPasswordNewConfirm, name='userPasswordNewConfirm'),
    re_path(r'^anunciante/confirmation/new/$', views.userConfirmationNew, name='userConfirmationNew'),
    re_path(r'^anunciante/(?P<anuncianteId>[0-9]+)/edit/(?P<token>\w+)/$', views.userConfirmationNewConfirm, name='userConfirmationNewConfirm'),

    re_path(r'^anuncio$', views.anuncioList,  name='anuncioList'),
    re_path(r'^anuncio/$', views.anuncioList,  name='anuncioList'),
    re_path(r'^anuncio/(?P<categoriaId>[0-9]+)/$', views.anuncioList,  name='anuncioList'),
    re_path(r'^anuncio/new/$', views.anuncioNew, name='anuncioNew'),
    re_path(r'^anuncio/s(?P<anuncioId>[0-9]+)/$', views.anuncioShow, name='anuncioShow'),
    re_path(r'^anuncio/(?P<anuncioId>[0-9]+)/delete/$', views.anuncioDelete, name='anuncioDelete'),
    re_path(r'^anuncio/(?P<anuncioId>[0-9]+)/pause/$', views.anuncioPause, name='anuncioPause'),
    re_path(r'^anuncio/(?P<anuncioId>[0-9]+)/edit/$', views.anuncioEdit, name='anuncioEdit'),
    re_path(r'^anuncio/(?P<anuncioId>[0-9]+)/renew/$', views.anuncioRenew, name='anuncioRenew'),

    re_path(r'^anuncioD$', views.anuncioDList,  name='anuncioDList'),
    re_path(r'^anuncioD/$', views.anuncioDList,  name='anuncioDList'),
    re_path(r'^anuncioD/new/$', views.anuncioDNew, name='anuncioDNew'),
    re_path(r'^anuncioD/s(?P<anuncioDId>[0-9]+)/$', views.anuncioDShow, name='anuncioDShow'),
    re_path(r'^anuncioD/(?P<anuncioDId>[0-9]+)/delete/$', views.anuncioDDelete, name='anuncioDDelete'),
    re_path(r'^anuncioD/(?P<anuncioDId>[0-9]+)/pause/$', views.anuncioPause, name='anuncioDPause'),
    re_path(r'^anuncioD/(?P<anuncioDId>[0-9]+)/edit/$', views.anuncioDEdit, name='anuncioDEdit'),
    re_path(r'^anuncioD/(?P<anuncioDId>[0-9]+)/renew/$', views.anuncioDRenew, name='anuncioDRenew'),

    re_path(r'^contato/show/$', views.contatoShow, name='contatoShow'),

    re_path(r'^failure/(?P<pagamentoId>[-A-Za-z0-9_]+)/$', views.paymentFailure,  name='paymentFailure'),
    re_path(r'^pending/(?P<pagamentoId>[-A-Za-z0-9_]+)/$', views.paymentPending,  name='paymentPending'),
    re_path(r'^success/(?P<pagamentoId>[-A-Za-z0-9_]+)/$', views.paymentSuccess,  name='paymentSuccess'),
    re_path(r'^webhook/$', views.paymentWebhook,  name='paymentWebhook'),
    re_path(r'^process/(?P<preferenceId>[-A-Za-z0-9_]+)/getForm/(?P<anuncioId>[-A-Za-z0-9_]+)/$', views.paymentProcess,  name='paymentProcess'),
    re_path(r'^pagamento/$', views.pagamentoList, name='pagamentoList'),
    re_path(r'^pagamento/(?P<pagamentoId>[0-9]+)/$', views.pagamentoShow, name='pagamentoShow'),
    re_path(r'^pagamento/(?P<pagamentoId>[0-9]+)/edit/$', views.pagamentoEdit, name='pagamentoEdit'),
    re_path(r'^pagamento/(?P<pagamentoId>[0-9]+)/delete/$', views.pagamentoDelete, name='pagamentoDelete'),

    re_path(r'^ensaio/$', views.ensaioList, name='ensaioList'),
    re_path(r'^ensaio/new/$', views.ensaioNew, name='ensaioNew'),
    re_path(r'^ensaio/(?P<ensaioId>[0-9]+)/$', views.ensaioShow, name='ensaioShow'),
    re_path(r'^ensaio/(?P<ensaioId>[0-9]+)/delete/$', views.ensaioDelete, name='ensaioDelete'),
    re_path(r'^ensaio/(?P<ensaioId>[0-9]+)/edit/$', views.ensaioEdit, name='ensaioEdit'),

    re_path(r'^busca/$', views.busca, name='busca'),

    re_path(r'^caracteristica/$', views.caracteristicaList, name='caracteristicaList'),
    re_path(r'^caracteristica/new/$', views.caracteristicaNew, name='caracteristicaNew'),
    re_path(r'^caracteristica/(?P<caracteristicaId>[0-9]+)/$', views.caracteristicaShow, name='caracteristicaShow'),
    re_path(r'^caracteristica/(?P<caracteristicaId>[0-9]+)/delete/$', views.caracteristicaDelete, name='caracteristicaDelete'),
    re_path(r'^caracteristica/(?P<caracteristicaId>[0-9]+)/edit/$', views.caracteristicaEdit, name='caracteristicaEdit'),

    re_path(r'^informacao/$', views.informacaoList, name='informacaoList'),
    re_path(r'^informacao/new/$', views.informacaoNew, name='informacaoNew'),
    re_path(r'^informacao/(?P<informacaoId>[0-9]+)/$', views.informacaoShow, name='informacaoShow'),
    re_path(r'^informacao/(?P<informacaoId>[0-9]+)/delete/$', views.informacaoDelete, name='informacaoDelete'),
    re_path(r'^informacao/(?P<informacaoId>[0-9]+)/edit/$', views.informacaoEdit, name='informacaoEdit'),

    re_path(r'^atende/$', views.atendeList, name='atendeList'),
    re_path(r'^atende/new/$', views.atendeNew, name='atendeNew'),
    re_path(r'^atende/(?P<atendeId>[0-9]+)/$', views.atendeShow, name='atendeShow'),
    re_path(r'^atende/(?P<atendeId>[0-9]+)/delete/$', views.atendeDelete, name='atendeDelete'),
    re_path(r'^atende/(?P<atendeId>[0-9]+)/edit/$', views.atendeEdit, name='atendeEdit'),

    re_path(r'^formaPagamento/$', views.formaPagamentoList, name='formaPagamentoList'),
    re_path(r'^formaPagamento/new/$', views.formaPagamentoNew, name='formaPagamentoNew'),
    re_path(r'^formaPagamento/(?P<formaPagamentoId>[0-9]+)/$', views.formaPagamentoShow, name='formaPagamentoShow'),
    re_path(r'^formaPagamento/(?P<formaPagamentoId>[0-9]+)/delete/$', views.formaPagamentoDelete, name='formaPagamentoDelete'),
    re_path(r'^formaPagamento/(?P<formaPagamentoId>[0-9]+)/edit/$', views.formaPagamentoEdit, name='formaPagamentoEdit'),
    
    re_path(r'^olhos/$', views.olhosList, name='olhosList'),
    re_path(r'^olhos/new/$', views.olhosNew, name='olhosNew'),
    re_path(r'^olhos/(?P<olhosId>[0-9]+)/$', views.olhosShow, name='olhosShow'),
    re_path(r'^olhos/(?P<olhosId>[0-9]+)/delete/$', views.olhosDelete, name='olhosDelete'),
    re_path(r'^olhos/(?P<olhosId>[0-9]+)/edit/$', views.olhosEdit, name='olhosEdit'),

    re_path(r'^categoria/$', views.categoriaList, name='categoriaList'),
    re_path(r'^categoria/new/$', views.categoriaNew, name='categoriaNew'),
    re_path(r'^categoria/(?P<categoriaId>[0-9]+)/$', views.categoriaShow, name='categoriaShow'),
    re_path(r'^categoria/(?P<categoriaId>[0-9]+)/delete/$', views.categoriaDelete, name='categoriaDelete'),
    re_path(r'^categoria/(?P<categoriaId>[0-9]+)/edit/$', views.categoriaEdit, name='categoriaEdit'),

    re_path(r'^idioma/$', views.idiomaList, name='idiomaList'),
    re_path(r'^idioma/new/$', views.idiomaNew, name='idiomaNew'),
    re_path(r'^idioma/(?P<idiomaId>[0-9]+)/$', views.idiomaShow, name='idiomaShow'),
    re_path(r'^idioma/(?P<idiomaId>[0-9]+)/delete/$', views.idiomaDelete, name='idiomaDelete'),
    re_path(r'^idioma/(?P<idiomaId>[0-9]+)/edit/$', views.idiomaEdit, name='idiomaEdit'),

    re_path(r'^seios/$', views.seiosList, name='seiosList'),
    re_path(r'^seios/new/$', views.seiosNew, name='seiosNew'),
    re_path(r'^seios/(?P<seiosId>[0-9]+)/$', views.seiosShow, name='seiosShow'),
    re_path(r'^seios/(?P<seiosId>[0-9]+)/delete/$', views.seiosDelete, name='seiosDelete'),
    re_path(r'^seios/(?P<seiosId>[0-9]+)/edit/$', views.seiosEdit, name='seiosEdit'),

    re_path(r'^biotipo/$', views.biotipoList, name='biotipoList'),
    re_path(r'^biotipo/new/$', views.biotipoNew, name='biotipoNew'),
    re_path(r'^biotipo/(?P<biotipoId>[0-9]+)/$', views.biotipoShow, name='biotipoShow'),
    re_path(r'^biotipo/(?P<biotipoId>[0-9]+)/delete/$', views.biotipoDelete, name='biotipoDelete'),
    re_path(r'^biotipo/(?P<biotipoId>[0-9]+)/edit/$', views.biotipoEdit, name='biotipoEdit'),

    re_path(r'^cidade/$', views.cidadeList, name='cidadeList'),
    re_path(r'^cidade/new/$', views.cidadeNew, name='cidadeNew'),
    re_path(r'^cidade/(?P<cidadeId>[0-9]+)/$', views.cidadeShow, name='cidadeShow'),
    re_path(r'^cidade/(?P<cidadeId>[0-9]+)/delete/$', views.cidadeDelete, name='cidadeDelete'),
    re_path(r'^cidade/(?P<cidadeId>[0-9]+)/edit/$', views.cidadeEdit, name='cidadeEdit'),
    re_path(r'^filtraCidade/(?P<estadoId>[0-9]+)/$', views.filtraCidade, name='fitraCidade'),
    re_path(r'^alteraRegiao/$', views.alteraRegiao, name='alteraRegiao'),
    re_path(r'^pegaEstados/$', views.pegaEstados, name='pegaEstados'),

    re_path(r'^estado/$', views.estadoList, name='estadoList'),
    re_path(r'^estado/new/$', views.estadoNew, name='estadoNew'),
    re_path(r'^estado/(?P<estadoId>[0-9]+)/$', views.estadoShow, name='estadoShow'),
    re_path(r'^estado/(?P<estadoId>[0-9]+)/delete/$', views.estadoDelete, name='estadoDelete'),
    re_path(r'^estado/(?P<estadoId>[0-9]+)/edit/$', views.estadoEdit, name='estadoEdit'),


    re_path(r'^plano/$', views.planoList, name='planoList'),
    re_path(r'^plano/new/$', views.planoNew, name='planoNew'),

mysite/models/AnuncioD.py
#!/usr/bin/python
#-*- coding: utf-8 -*-
from django.db import models
from django.utils.encoding import smart_str
from mysite.models import *
from mysite.settings import BASE_PATH
from django.utils.translation import gettext_lazy as _
from django.core.files.storage import default_storage
from django.core.validators import  MinValueValidator 

class AnuncioD (models.Model):
    def content_file_name(instance, filename):
        filename = filename.replace(" ", "").replace("(", "").replace(")", "")
        path = 'anuncio_dupla/'+ str(instance.anunciante.id)+'/'+ filename
        if default_storage.exists(path):
            return 'anuncio_dupla/'+ str(instance.anunciante.id)+ '/1_'+ filename
        else:
            return  path
    
    anunciante = models.ForeignKey(Anunciante, 
    related_name = 'anuncianteD',
    verbose_name = 'anunciante',
    on_delete = models.PROTECT,
    blank=False)

    plano = models.ForeignKey(Plano, verbose_name='Plano', on_delete=models.PROTECT, blank=False, null = False, default = 1,  help_text="Planos Destaque contém 4 ensaios com 10 fotos e aparecem no topo. Planos Básicos contem 2 ensaios com 10 fotos.")

    estado = models.ForeignKey(Estado, verbose_name='Estado', on_delete=models.PROTECT, blank=False, null = False, default = 1)

    cidade = models.ForeignKey(Cidade, verbose_name='Cidade', on_delete=models.PROTECT, blank=False, null = False, default = 1)

    categoria1 = models.ForeignKey(Categoria, related_name = 'categoria1', verbose_name='Categoria', on_delete=models.PROTECT, blank=False, null = False)

    categoria2 = models.ForeignKey(Categoria, related_name = 'categoria2', verbose_name='Categoria da Parceira', on_delete=models.PROTECT, blank=False, null = False)  

    nome = models.CharField('Nome', max_length=50, blank=False, help_text='Nome para o anúncio. Exemplo: "Julia e Camis"')

    primeiroNome1 = models.CharField(u'Primeiro Nome', max_length=50, blank=False, null=False, help_text='Seu primeiro nome, como o cliente irá te chamar. Exemplo: "Julia"')

    primeiroNome2 = models.CharField(u'Primeiro Nome da Parceira', max_length=50, blank=False, null=False, help_text='Primeiro nome de sua parceira, como o cliente irá chama-la. Exemplo: "Camis"')

    idade1 =  models.IntegerField(u'Idade', validators=[MinValueValidator(18)], blank=False)

    idade2 =  models.IntegerField(u'Idade da Parceira', validators=[MinValueValidator(18)], blank=False)

    peso1 =  models.FloatField(u'Peso', blank=False)

    peso2 =  models.FloatField(u'Peso da Parceira', blank=False)

    altura1 =  models.FloatField(u'Altura', blank=False,  help_text='Exemplo: 1,65 para 1m e 65cm')

    altura2 =  models.FloatField(u'Altura da Parceira', blank=False,  help_text='Exemplo: 1,65 para 1m e 65cm')

    olhos1 = models.ForeignKey(Olhos, related_name = 'olhos1', verbose_name='Olhos', on_delete=models.PROTECT, blank=False, null = False)

    olhos2 = models.ForeignKey(Olhos, related_name = 'olhos2', verbose_name='Olhos da Parceira', on_delete=models.PROTECT, blank=False, null = False)

    seios1 = models.ForeignKey(Seios, related_name = 'seios1', verbose_name='Seios', on_delete=models.PROTECT, blank=False, null = False)

    seios2 = models.ForeignKey(Seios, related_name = 'seios2', verbose_name='Seios da Parceira', on_delete=models.PROTECT, blank=False, null = False) 

    biotipo1 = models.ForeignKey(Biotipo, related_name = 'biotipo1', verbose_name='Biotipo', on_delete=models.PROTECT, blank=False, null = False)

    biotipo2 = models.ForeignKey(Biotipo, related_name = 'biotipo2', verbose_name='Biotipo da Parceira', on_delete=models.PROTECT, blank=False, null = False) 

    idiomas = models.ManyToManyField(Idioma, verbose_name="Idiomas")

    telefone = models.CharField('Telefone', max_length=50, blank=False,  help_text='Este é o número pelo qual os visitantes entrarão em contato. Recomendamos que possua whatsapp.')

    local = models.BooleanField(_('Possui local'), default=False,  blank=True,  help_text='Assinale se possui local para atendimento')

    formasPagamento = models.ManyToManyField(FormaPagamento, verbose_name="Formas de Pagamento",  help_text='Formas de pagamento que aceitam')

    texto = models.TextField('Texto', max_length=10000, blank = True,  help_text='Conte sobre vocês, seus serviços, como interagem e o por quê devem entrar em contato. Ressalte seus pontos fortes, o que gostam de fazer.')

    cache =  models.IntegerField(u'Cachê', blank=False,  help_text='Valor cobrado pelo serviço. Se preferir combinar, deixe o valor 0 que aparecerá "A combinar" no anúncio.')

    onlyfans1 = models.CharField('Onlyfans', max_length=50, blank=True,  help_text="Caso você possua, endereço do Onlyfans.")

    onlyfans2 = models.CharField('Onlyfans da Parceira', max_length=50, blank=True,  help_text="Caso sua parceira possua, endereço do Onlyfans.")

    privacy1 = models.CharField('Privacy', max_length=50, blank=True,  help_text="Caso você possua, endereço do Privacy.")

    privacy2 = models.CharField('Privacy da Parceira', max_length=50, blank=True,  help_text="Caso sua parceira possua, endereço do Privacy.")

    twitter1 = models.CharField('Twitter', max_length=50, blank=True,  help_text="Caso você possua, endereço do Twitter.")

    twitter2 = models.CharField('Twitter da Parceira', max_length=50, blank=True,  help_text="Caso sua parceira possua, endereço do Twitter.")

    instagram1 = models.CharField('Instagram', max_length=50, blank=True,  help_text="Caso você possua, endereço do Instagram.")

    instagram2 = models.CharField('Instagram da Parceira', max_length=50, blank=True,  help_text="Caso sua parceira possua, endereço do Instagram.")

    atende = models.ManyToManyField(Atende, verbose_name="Atende",  help_text='Assinale o público que atende.')

    caracteristicas1 = models.ManyToManyField(Caracteristica, related_name = 'caracteristicas1',verbose_name="Características Físicas",  help_text='Assinale as características físicas na qual você se enquadra.')

    caracteristicas2 = models.ManyToManyField(Caracteristica, related_name = 'caracteristicas2', verbose_name="Características Físicas da Parceira",  help_text='Assinale as características físicas na qual sua parceira se enquadra.')

    informacoes = models.ManyToManyField(Informacao, verbose_name="Informações",  help_text='Assinale os itens que se enquadram nos serviços que executam.')

    capa = models.FileField('Foto principal', upload_to= content_file_name, blank=False,  help_text='Utilize uma foto que ambas apareçam juntas. Esta foto é a que chamará atenção para seu anúncio.')

    data_ini = models.DateTimeField(blank=True, null = True)

    data_exp = models.DateTimeField('Data de expiração do anúncio', auto_now_add=False, auto_now = False, blank=True, null = True)

    data_pause = models.DateTimeField(blank=True, null = True)

    pausado = models.BooleanField(default=False,  blank=True)
    

    def __str__(self):
      a = smart_str(self.nome)
      return a

    class Meta:

        verbose_name = u'AnúncioD'
        ordering = ['-nome']

templates/anuncioD/form.html
{% extends '_template2.html' %}

{% load static %}
{% load i18n %}
{% load mysite_tags %}

{% block style %}
  <link rel="stylesheet" href="{% static 'plugins/datepicker/datepicker3.css' %}">
{% endblock %}

{% block header %}{{ title|safe }}{% endblock %}

{% block content %}
    <div class="container">
      {% include '_form.html' with form=form button=button %}
    </div>
{% endblock %}

{% block script %}
<script type="text/javascript" src="{% static 'assets/js/bootstrap-uploadprogress.js' %}"> </script>  
<script type="text/javascript">
    $('ul').removeClass('form-control');
    $('ul input').removeClass('form-control');
    $("#id_form").uploadprogress();
    
    $('#id_estado').change( function() {
        var form = $(this);
        $.ajax({
          url: "/filtraCidade/" +  $(this).val(),
          dataType: 'json',
          success: function (data) {
            $('#id_cidade').html("");
            
            if (data.length == 0){
                $('#id_cidade').append($('<option>', {
                  text: 'Não há anúncios neste estado.'
                }));
            }
            else{
                $('#id_cidade').append($('<option>', {
                  text: 'Selecione uma cidade'
                }));
            }
            for (var i = 0; i < data.length; i++) {
              $('#id_cidade').append($('<option>', {
                value: data[i].id,
                text: data[i].data
              }));
            }   

          },
          error: function(data){ 
          },
        });
      })
    $('#id_cidade').change( function() {
      var form = $(this);
      $.ajax({
        url: "/filtrarPlano/" +  $(this).val(),
        dataType: 'json',
        success: function (data) {
          $('#id_plano').html("");
          
          if (data.length == 0){
              $('#id_plano').append($('<option>', {
                text: 'Não há plano para esta cidade'
              }));
          }
          else{
              $('#id_plano').append($('<option>', {
                text: 'Selecione um plano'
              }));
          }
          for (var i = 0; i < data.length; i++) {
            $('#id_plano').append($('<option>', {
              value: data[i].id,
              text: data[i].data
            }));
          }   

        },
        error: function(data){ 
        },
      });
    })

</script>
{% endblock %}

templates/anuncioD/list.html
{% extends '_template2.html' %}

{% load static %}
{% load i18n %}
{% load mysite_tags %}

{% block style %}     
    <!--     Fonts and icons     -->
  <link href='http://fonts.googleapis.com/css?family=Roboto:400,700,300' rel='stylesheet' type='text/css'>
{% endblock %}

{% block header %}{{ title|safe }}{% endblock %}

{% block content %}
  
  {% with 'AnuncioD' as model %}
    {% include '_modal.html' with modal=model %}
    <body>
      <div class="container mt-4">
        <div class="row">   
          <div class="col-12">
            {% if anuncios_destaques or anuncios_basicos %}  

              {% if anuncios_destaques %}  
                <div class="list-header">Destaques</div>
                <div class="list-body row">
                  {% for anuncio_destaque in anuncios_destaques %}
                    <div class="col-12 col-sm-4 col-lg-2">
                      <a href="{% url 'anuncioDShow' anuncio_destaque.id %}">
                        <div class="list-body__item">
                          <img class="capa" border="0" src="{{ anuncio_destaque.capa.url }}" >
                          <span> 
                            {{ anuncio_destaque.nome }}
                          </span>
                        </div>
                      </a> 
                    </div>
                  {% endfor %}
                  </div>
              {% endif %}

              {% if anuncios_basicos %}  
                <div class="list-header">Modelos</div>
                <div class="list-body row">
                  {% for anuncio_basico in anuncios_basicos %}
                    <div class="col-12 col-sm-4 col-lg-2">
                      <a href="{% url 'anuncioDShow' anuncio_basico.id %}">
                        <div class="list-body__item">
                          <img class="capa" border="0" src="{{ anuncio_basico.capa.url }}" >
                          <span> 
                            {{ anuncio_basico.nome }}
                          </span>
                        </div>
                      </a> 
                    </div>
                  {% endfor %}
                  </div>
              {% endif %}
            {% else %} 
              <a><center>Infelizmente não encontramos nenhum anúncio.</center></a>
            {% endif %}
          </div>
        </div>
      </div>
    </body>
  {% endwith %}
{% endblock content %}


{% block script %} 
  <script src="{% static 'plugins/datatables/jquery.dataTables.min.js' %}"></script>
  <script src="{% static 'plugins/datatables/dataTables.bootstrap.min.js' %}"></script>
  <script>
    var id_list = 'listAnuncioD';
    var id_modal = 'deleteModalAnuncioD';
  </script>
  <script type="text/javascript" src="{% static 'assets/js/bootstrap.js' %}"></script>
  <script async src="https://www.googletagmanager.com/gtag/js?id=G-ZYYED20CQF"></script>
  <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());

    gtag('config', 'G-ZYYED20CQF');
  </script>
              
{% endblock %}